# /Users/sebastjanlajkovic/.config/tmuxinator/s4-review-mobile-app.yml

name: review-mobile-app
root: .

windows:
  - Default:
      layout: main-vertical
      panes:
        - npm test
        - ionic serve
        - watch docker ps
        - code .
  - Logs:
  - Console:
